--- Log started at 2025-09-28 15:51:30 ---
[INFO] Discovering functions in './metrics/'...
[WARNING] - Could not load 'ai_llm_generic_call': module 'metrics.ai_llm_generic_call' has no attribute 'ai_llm_generic_call'
[INFO]   - Loaded function: 'bus_factor_metric'
[INFO]   - Loaded function: 'calculate_license_score'
[INFO]   - Loaded function: 'calculate_size_score'
[INFO]   - Loaded function: 'code_quality'
[INFO]   - Loaded function: 'dataset_and_code_present'
[WARNING] - Could not load 'dataset_quality': No module named 'pandas'
[INFO]   - Loaded function: 'performance_claims_metric'
[INFO]   - Loaded function: 'rampup_time_metric'
[INFO] Reading and parsing tasks from './tasks.txt'...
[INFO] Queued: bus_factor_metric(...) with weight 3.0
[WARNING] Skipped line 2: 'calculate_license_score' expects 4 args, but 3 keys were provided.
[INFO] Queued: calculate_size_score(...) with weight 1.0
[INFO] Queued: code_quality(...) with weight 2.0
[INFO] Queued: dataset_and_code_present(...) with weight 3.0
[WARNING] Skipped line 6: Function 'dataset_quality' not found.
[INFO] Queued: performance_claims_metric(...) with weight 2.0
[INFO] Queued: rampup_time_metric(...) with weight 3.0
[INFO] --- Starting all processes ---
[INFO] --- Collecting results ---
[7184] [INFO] Starting bus factor check based on README content...
[7184] [INFO] No mention of contributors found in README -> Score = 0.0
[7184] [INFO] Finished calculation. Score=0.00, Time=0.002s
[17940] [INFO] Starting size score calculation for model of 3454102158 bytes...
[17940] [INFO] Model size: 3.22 GB
[17940] [DEBUG] Raspberry Pi score: 0.0
[17940] [DEBUG] Jetson Nano score: 0.0
[17940] [DEBUG] Desktop PC score: 1.0
[17940] [DEBUG] AWS Server score: 1.0
[17940] [INFO] Finished calculation. Average Score=0.50, Time=0.0035s
[23384] Running PyLint on 'bert'...
[44556] [INFO] Starting dataset-in-readme check...
[44556] [INFO] Dataset mention found in README: False
[44556] [INFO] Finished calculation. Score=0.00, Time=0.002s
[3324] [INFO] Calling LLM for performance claims on 'bert-base-uncased_README.md.txt'...
[43428] [INFO] Calling LLM for ramp-up time on 'bert-base-uncased_README.md.txt'...
[23384] [WARNING] Could not find PyLint score line in output for 'https://github.com/google-research/bert'.
[23384] [DEBUG] PyLint output for 'https://github.com/google-research/bert':
---BEGIN---
************* Module https://github.com/google-research/bert
https://github.com/google-research/bert:1:0: F0001: No module named https://github.com/google-research/bert (fatal)

---END---
[3324] [WARNING] Received no response from LLM for performance claims metric.
[43428] [WARNING] Received no response from LLM for ramp-up time metric.
[INFO] --- All processes have completed ---
--- Log ended at 2025-09-28 15:52:02 ---
